import type { MissionFailure } from "@/types/mission-intel";

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

export function buildMissionArchiveHtml(missions: MissionFailure[]): string {
  const rows = [...missions]
    .sort((a, b) => b.year - a.year)
    .map(
      (m) =>
        `<tr><td><b>${escapeHtml(m.name)}</b></td><td>${m.year}</td><td>${escapeHtml(m.agency)}</td><td>${escapeHtml(m.category)}</td><td>${escapeHtml(m.severity)}</td><td>$${m.cost}M</td><td>${escapeHtml(m.type)}</td></tr>`,
    )
    .join("");

  const totalCost = missions.reduce((s, m) => s + m.cost, 0);
  const deaths = missions.reduce((s, m) => s + m.casualties, 0);

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title>AstroFlow Mission Failure Archive</title>
<style>
body{font-family:Segoe UI,system-ui,sans-serif;background:#fafafa;color:#18181b;padding:32px;max-width:1100px;margin:auto}
h1{color:#27272a;font-family:ui-monospace,Consolas,monospace;font-weight:700;letter-spacing:.02em;font-size:1.35rem}
.meta{color:#52525b;margin-bottom:24px;font-size:14px;line-height:1.5}
table{width:100%;border-collapse:collapse;background:#fff;box-shadow:0 1px 3px rgba(0,0,0,.06);border:1px solid #e4e4e7}
th{background:#18181b;color:#fafafa;padding:10px 12px;font-size:12px;text-align:left;font-weight:600}
td{padding:9px 12px;border-bottom:1px solid #e4e4e7;font-size:13px;vertical-align:top}
tr:hover{background:#f4f4f5}
</style>
</head>
<body>
<h1>ASTROFLOW — Mission failure archive</h1>
<p class="meta"><strong>${missions.length}</strong> missions · est. <strong>$${(totalCost / 1000).toFixed(1)}B</strong> cost lost · <strong>${deaths}</strong> recorded fatalities (where applicable). Educational / summary export.</p>
<table>
<thead><tr><th>Mission</th><th>Year</th><th>Agency</th><th>Category</th><th>Severity</th><th>Cost</th><th>Type</th></tr></thead>
<tbody>${rows}</tbody>
</table>
<p class="meta" style="margin-top:28px">Generated by AstroFlow. See in-app for full descriptions, root causes, and lessons learned.</p>
</body>
</html>`;
}
